# Uncomment this line to define a global platform for your project

#官方Cocoapods的源
#source 'https://github.com/CocoaPods/Specs.git'

#本地私有源
#source 'https://git.oschina.net/scx/JLSpecs.git'

# 修改过得第三方库
# 1.WMPageController：（WMScrollView.m）解决 PlayerCell 中调节视频进度被WMScrollView拦截的问题

platform :ios, '8.0'
use_frameworks!

target ‘CodeDemo’ do
    pod 'SDWebImage', '~> 3.7.6'

    #UI
    pod 'SDCycleScrollView','~> 1.64'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
