
platform :ios, '8.0'
use_frameworks!

target ‘CodeDemo’ do
    pod 'SDWebImage', '~> 3.7.6'
    pod 'TZImagePickerController'
    pod 'IQKeyboardManager'

    #UI
    pod 'SDCycleScrollView','~> 1.64'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
